### PR TITLE
pluralization support

### PR DESCRIPTION
**Pull request by gshegosh**
This is basic pluralization support.

Can be used like that:
i18n\`You have ${counter}:u(1:{} event||2:{} events)\`

where :u() is new suffix I've implemented. 1: signifies the variant for singular value and 2: for plural one. {} is replaced with the value itself. So the above will render to:

You have 1 event

for counter == 1 and to:

You have 172 events

for counter == 172.

I've also implemented more complex ruleset for Polish language:

{ i18n\`Masz ${this.test3}:u(0:{} zdarzeń||1:{} zdarzenie||2:{} zdarzenia)\` }

We have 3 noun variants and it's possible to properly use them thanks to my implementation.

I believe the syntax leaves it open for others to implement rules for their languages. Perhaps the flexing code should be extracted and made configurable, but I'll leave it to others to do so, if they deem it necessary.

### CODE REVIEW

**Comment by skolmer** [comment]
Thanks for the pull request.
Pluralization is a good point. Haven't thought about this in detail yet but how about using nested templates like this:

```js
i18n`You have ${counter} ${(counter === 1)?i18n`event`:i18n`events`}`
```

The translations will look like:
```json
{
    "You have ${0} ${1}": "Sie haben ${0} ${1}",
    "event": "Ereignis",
    "events": "Ereignisse"
}
```

This is already possible but I'm not sure about the edge-cases.

**Comment by gshegosh** [comment]
I think it's better to extract this logic (counter === 1 or - if you look at my PR much more complex condition to choose one of three variants in Polish) so we don't have to repeat it with every i18n string.

Also, you're not always going to use the "${0} ${1}" format. For instance, you might want:

n=0 --> You have no messages.
n=1 --> You have one message.
n>1 --> You have {n} messages.

The syntax I've proposed makes it possible to put such logic away from i18n string itself and even use different "steps" for different languages. What I'm not sure is if it should be hardcoded in the library, or perhaps overrideable via options.

**Comment by skolmer** [comment]
I really like the flexibility of of nested template literals because you can write even more complex logic in js like:
```js
const pluralizedEvents = (counter) => {
    switch(counter === 1)
        case 1:
            return i18n`one event`
        case 2:
            return i18n`${i18n`two`} events`
        default:
            return i18n`${counter} events`
}
i18n`You have ${pluralizedEvents(counter)}`
```

```json
{
    "You have ${0} ${1}": "Sie haben ${0} ${1}",
    "one event": "ein Ereignis",
    "${0} events": "${0} Ereignisse",
    "two": "zwei"
}
```

I also understand the requirement to write custom suffixes and like the idea. We should think about an api to add custom suffix functions. Proposals are welcome :+1:

**Comment by gshegosh** [comment]
Nested templates are probably the way to go, I've just noticed a silly thing about my PR -- I hardcoded part of the message :)

**Comment by skolmer** [comment]
I will create an issue for customizable suffix functions and close this PR

**Pull request closed without merging**
